services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    container_name: pp_challenge_web
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
  api:
    container_name: pp_challenge_api
    build:
        context: .
        dockerfile: api.Dockerfile
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run mock
    ports:
      - "3030:3030"
    environment:
      - CHOKIDAR_USEPOLLING=true
