services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    container_name: pp_challenge_web
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
  api:
    image: clue/json-server
    container_name: pp_challenge_api
    tty: true
    volumes:
      - ./mock/db.json:/data/db.json
    ports:
      - "3030:80"
